"""create packages table

Revision ID: 519a82cccc97
Revises: 93c5bf3c4ed9
Create Date: 2020-10-15 18:59:54.782266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '519a82cccc97'
down_revision = '93c5bf3c4ed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
